site_name: TP Powershell CESI
dev_addr: '0.0.0.0:4000'
site_author: 'Baptiste DENEUVE'
theme: 'material'
markdown_extensions:
  #- codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
plugins:
  - search
  - to-pdf :
      download_link: header
      toc_title: "Sommaire"
      copyright: "Test"
      cover_subtitle: "Test"
  - git-revision-date-localized:
      enable_creation_date: false
      type : datetime



  
